eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
myhotel-microservices:
  hotel-inventory-service:
    endpoints:
      base-uri: /api/v1/hotelinventory
      get-hotel-inventory: /hotel/{hotel_id}
      get-hotel-room-inventory: /hotel/{hotel_id}/room/{room_number}
      put-hotel-inventory-metadata: /hotel/{hotel_id}
      put-hotel-room-inventory: /hotel/{hotel_id}/room/{room_number}
      post-hotel-room-inventory: /hotel/{hotel_id}/room
      delete-hotel-inventory: /hotel/{hotel_id}
      delete-hotel-room-inventory: /hotel/{hotel_id}/room/{room_number}
  guest-service:
    endpoints:
      base-uri: /api/v1/guests
      get-guest-profile: /guest/{guest_id}
      get-guest-username-password: /guest/{guest_id}
      get-guest-stay: /guest/{guest_id}/stay/{stay_id}
      get-guest-creditcard: /guest/{guest_id}/card/{card_id}
      post-guest-stay: /guest/{guest_id}/stay
      post-guest-creditcard: /guest/{guest_id}/creditcard
      delete-guest-stay: /guest/{guest_id}/stay/{stay_id}
      delete-guest-creditcard: /guest/{guest_id}/card/{card_id}
      put-guest-stay: /guest/{guest_id}/stay/{stay_id}
      put-guest-creditcard: /guest/{guest_id}/card/{card_id}
   
