eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
myhotel-microservices:
  hotel-inventory-service:
    endpoints:
        get-all-hotel-inventories: /api/v1/hotelinventory
        get-hotel-inventory: /api/v1/hotelinventory/hotel/{hotel_id}
        get-hotel-room-inventory: /api/v1/hotelinventory/hotel/{hotel_id}/room/{room_number}
        put-hotel-inventory-metadata: /api/v1/hotelinventory/hotel/{hotel_id}
        put-hotel-room-inventory: /api/v1/hotelinventory/hotel/{hotel_id}/room/{room_number}
        post-to-hotel-inventories: /api/v1/hotelinventory
        post-hotel-room-inventory: /api/v1/hotelinventory/hotel/{hotel_id}/room
        delete-hotel-inventory: /api/v1/hotelinventory/hotel/{hotel_id}
        delete-hotel-room-inventory: /api/v1/hotelinventory/hotel/{hotel_id}/room/{room_number}
