eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
myhotel-microservices:
  hotel-inventory-service:
    endpoints:
      base-uri: /api/v1/hotelinventory
      get-hotel-inventory: /hotel/{hotel_id}
      get-hotel-room-inventory: /hotel/{hotel_id}/room/{room_number}
      put-hotel-inventory-metadata: /hotel/{hotel_id}
      put-hotel-room-inventory: /hotel/{hotel_id}/room/{room_number}
      post-hotel-room-inventory: /hotel/{hotel_id}/room
      delete-hotel-inventory: /hotel/{hotel_id}
      delete-hotel-room-inventory: /hotel/{hotel_id}/room/{room_number}
  guest-service:
    endpoints:
      base-uri: /api/v1/guests
      get-guest-profile: /guest/{guest_id}
      get-guest-stays: /guest/{guest_id}/stays
      get-guest-stay: /guest/{guest_id}/stays/stay/{stay_id}
      get-guest-creditcards: /guest/{guest_id}/creditcards
      get-guest-creditcard: /guest/{guest_id}/creditcards/card/{card_id}
      post-guest-stay: /guest/{guest_id}/stays
      post-guest-creditcard: /guest/{guest_id}/creditcards
      delete-guest-stay: /guest/{guest_id}/stays/stay/{stay_id}
      delete-guest-creditcard: /guest/{guest_id}/creditcards/card/{card_id}
      put-guest-stay: /guest/{guest_id}/stays/stay/{stay_id}
      put-guest-creditcard: /guest/{guest_id}/creditcards/card/{card_id}
   
